
import type { Metadata } from 'next'
import './globals.css'
import { lato, roboto } from './util/fonts'

import ThemeProvider from '../../providerMT'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider>  <body className={lato.className}>{children}</body></ThemeProvider>
    </html>
  )
}
